version: '2'

services:
  mongodb:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    ports:
      - "27017:27017"
    volumes:
      - '/home/shashank/mongo_data/db:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local